/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Role.CustomerRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import userinterface.WelcomeJPanel;

/**
 *
 * @author z9737
 */
public class CreateCustomerPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;

    /**
     * Creates new form CustomerPersonalInfoJPanel
     */
    public CreateCustomerPanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
    }

    /**
     * This method is called state within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHead = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        labelFirstName = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        labelLastName = new javax.swing.JLabel();
        labelDriversLiscence = new javax.swing.JLabel();
        txtRePassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();

        labelHead.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelHead.setText("Create User Account");

        btnCreate.setText("Create Account");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        labelFirstName.setText("Username *");

        labelLastName.setText("Password *");

        labelDriversLiscence.setText("Confirm Password *");

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelLastName)
                            .addComponent(labelFirstName)
                            .addComponent(labelDriversLiscence))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(labelHead))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnCreate)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelHead)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFirstName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLastName)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDriversLiscence))
                .addGap(18, 18, 18)
                .addComponent(btnCreate)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setComponentsBorderBlack() {
        txtUsername.setBorder(new LineBorder(new Color(128, 128, 128)));
        txtPassword.setBorder(new LineBorder(new Color(128, 128, 128)));
        txtRePassword.setBorder(new LineBorder(new Color(128, 128, 128)));
    }

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        setComponentsBorderBlack();

        if (!userinterface.Util.requireNotEmpty(this, txtUsername, txtPassword, txtRePassword)) {
            return;
        }

        if (data.UserDAO.isUsernameExist(txtUsername.getText())) {
            JOptionPane.showMessageDialog(this, "This username already exists, please choose another one!");
            return;
        }

        String password = String.valueOf(txtPassword.getPassword());
        String rePassword = String.valueOf(txtRePassword.getPassword());
        if (!password.equals(rePassword)) {
            JOptionPane.showMessageDialog(this, "Two passwords don't match!");
            return;
        }

        UserAccount user = new UserAccount();
        user.setUsername(txtUsername.getText());
        user.setPassword(password);
        user.setRole(new CustomerRole());
        data.UserDAO.createCustomer(user);

        JOptionPane.showMessageDialog(this, "Signing up successfully.");
        userProcessContainer.removeAll();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add(new WelcomeJPanel());
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
    }//GEN-LAST:event_txtPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel labelDriversLiscence;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelHead;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
