/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author zhangchuanqi
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        buttonPersonalInfo = new javax.swing.JButton();
        btnManageEnterprise = new javax.swing.JButton();
        buttonSearchClinic = new javax.swing.JButton();
        buttonSearchInsurance = new javax.swing.JButton();
        buttonInquries = new javax.swing.JButton();
        buttonPolicies = new javax.swing.JButton();
        customerContainer = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(200);

        buttonPersonalInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personal.png"))); // NOI18N
        buttonPersonalInfo.setText("Personal Information");
        buttonPersonalInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersonalInfoActionPerformed(evt);
            }
        });

        btnManageEnterprise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical.png"))); // NOI18N
        btnManageEnterprise.setText("Medical Information");
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });

        buttonSearchClinic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dental.png"))); // NOI18N
        buttonSearchClinic.setText("Search Clinic");
        buttonSearchClinic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchClinicActionPerformed(evt);
            }
        });

        buttonSearchInsurance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insurance.png"))); // NOI18N
        buttonSearchInsurance.setText("Search Insurance Plans");
        buttonSearchInsurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchInsuranceActionPerformed(evt);
            }
        });

        buttonInquries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversation.png"))); // NOI18N
        buttonInquries.setText("Inquries");
        buttonInquries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInquriesActionPerformed(evt);
            }
        });

        buttonPolicies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/policy.png"))); // NOI18N
        buttonPolicies.setText("Policies");
        buttonPolicies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPoliciesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonPolicies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonInquries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSearchClinic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageEnterprise, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPersonalInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSearchInsurance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(buttonPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSearchClinic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSearchInsurance, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonInquries, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPolicies, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel3);

        customerContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(customerContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPersonalInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersonalInfoActionPerformed
        customerContainer.removeAll();
        CustomerPersonalInfoJPanel customerPersonalInfoJPanel = new CustomerPersonalInfoJPanel(account);
        customerContainer.add(customerPersonalInfoJPanel);
        CardLayout layout = (CardLayout) customerContainer.getLayout();
        layout.next(customerContainer);
    }//GEN-LAST:event_buttonPersonalInfoActionPerformed

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed
        customerContainer.removeAll();
        CustomerMedicalInfoJPanel customerMedicalInfoJPanel = new CustomerMedicalInfoJPanel(account);
        customerContainer.add(customerMedicalInfoJPanel);
        CardLayout layout = (CardLayout) customerContainer.getLayout();
        layout.next(customerContainer);
    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void buttonSearchClinicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchClinicActionPerformed
        if (!data.UserDAO.isPersonalInfoComplete(account.getUsername())
            || !data.UserDAO.isMedicalInfoComplete(account.getUsername())) {
            JOptionPane.showMessageDialog(this, "Please compete personal and medical information first!");
            return;
        }
        customerContainer.removeAll();
        CustomerSearchClinicJPanel searchClinicJPanel = new CustomerSearchClinicJPanel(account);
        customerContainer.add(searchClinicJPanel);
        CardLayout layout = (CardLayout) customerContainer.getLayout();
        layout.next(customerContainer);
    }//GEN-LAST:event_buttonSearchClinicActionPerformed

    private void buttonSearchInsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchInsuranceActionPerformed
        if (!data.UserDAO.isPersonalInfoComplete(account.getUsername())
            || !data.UserDAO.isMedicalInfoComplete(account.getUsername())) {
            JOptionPane.showMessageDialog(this, "Please compete personal and medical information first!");
            return;
        }
        customerContainer.removeAll();
        CustomerSearchPolicyJPanel jpanel = new CustomerSearchPolicyJPanel(account);
        customerContainer.add(jpanel);
        CardLayout layout = (CardLayout) customerContainer.getLayout();
        layout.next(customerContainer);
    }//GEN-LAST:event_buttonSearchInsuranceActionPerformed

    private void buttonInquriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInquriesActionPerformed
        customerContainer.removeAll();
        CustomerInquiriesJPanel inquiryJPanel = new CustomerInquiriesJPanel(userProcessContainer, account, organization, enterprise);
        customerContainer.add(inquiryJPanel);
        CardLayout layout = (CardLayout) customerContainer.getLayout();
        layout.next(customerContainer);
    }//GEN-LAST:event_buttonInquriesActionPerformed

    private void buttonPoliciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPoliciesActionPerformed
        customerContainer.removeAll();
        CustomerPoliciesJPanel jpanel = new CustomerPoliciesJPanel(userProcessContainer, account, organization, enterprise);
        customerContainer.add(jpanel);
        CardLayout layout = (CardLayout) customerContainer.getLayout();
        layout.next(customerContainer);
    }//GEN-LAST:event_buttonPoliciesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton buttonInquries;
    private javax.swing.JButton buttonPersonalInfo;
    private javax.swing.JButton buttonPolicies;
    private javax.swing.JButton buttonSearchClinic;
    private javax.swing.JButton buttonSearchInsurance;
    private javax.swing.JPanel customerContainer;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
