/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InquiryWorkRequest;
import Business.WorkQueue.Message;
import java.awt.Container;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class CustomerSearchClinicJPanel extends javax.swing.JPanel {

    private UserAccount account;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public CustomerSearchClinicJPanel(UserAccount account) {
        initComponents();
        this.account = account;

        populateTable();
        BasicInternalFrameUI ui = (BasicInternalFrameUI) frameInquiry.getUI();
        Container north = (Container) ui.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();
        frameInquiry.setVisible(false);

        ui = (BasicInternalFrameUI) frameAppointment.getUI();
        north = (Container) ui.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();
        frameAppointment.setVisible(false);
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tableClinic.getModel();

        model.setRowCount(0);
        for (Enterprise enterprise : data.EnterpriseDAO.getAllbyType(Enterprise.EnterpriseType.DENTAL_CLINIC.getValue())) {
            Object[] row = new Object[3];
            row[0] = enterprise;
            row[1] = "";
            row[2] = "";
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableClinic = new javax.swing.JTable();
        buttonAppointment = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        frameInquiry = new javax.swing.JInternalFrame();
        labAvailable = new javax.swing.JLabel();
        labUnavailable = new javax.swing.JLabel();
        buttonConfirmInquiry = new javax.swing.JButton();
        buttonCancelInquiry = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInquiry = new javax.swing.JTextArea();
        buttonInquiry = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSearch1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        frameAppointment = new javax.swing.JInternalFrame();
        labAvailable1 = new javax.swing.JLabel();
        labUnavailable1 = new javax.swing.JLabel();
        buttonConfirmAppointment = new javax.swing.JButton();
        buttonCancelAppointment = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboNetwork1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        comboType1 = new javax.swing.JComboBox();

        tableClinic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clinic Name", "Address", "Rate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableClinic);

        buttonAppointment.setText("Make An Appointment");
        buttonAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAppointmentActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("Search Dental Clinic");

        frameInquiry.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        frameInquiry.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frameInquiry.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        frameInquiry.setEnabled(false);
        frameInquiry.setVisible(true);

        buttonConfirmInquiry.setText("Confirm");
        buttonConfirmInquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmInquiryActionPerformed(evt);
            }
        });

        buttonCancelInquiry.setText("Cancel");
        buttonCancelInquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelInquiryActionPerformed(evt);
            }
        });

        txtInquiry.setColumns(20);
        txtInquiry.setRows(5);
        jScrollPane2.setViewportView(txtInquiry);

        javax.swing.GroupLayout frameInquiryLayout = new javax.swing.GroupLayout(frameInquiry.getContentPane());
        frameInquiry.getContentPane().setLayout(frameInquiryLayout);
        frameInquiryLayout.setHorizontalGroup(
            frameInquiryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameInquiryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameInquiryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameInquiryLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labUnavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameInquiryLayout.createSequentialGroup()
                        .addComponent(buttonConfirmInquiry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancelInquiry)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameInquiryLayout.setVerticalGroup(
            frameInquiryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameInquiryLayout.createSequentialGroup()
                .addGroup(frameInquiryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labUnavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameInquiryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConfirmInquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancelInquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonInquiry.setText("Make An Inquiry");
        buttonInquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInquiryActionPerformed(evt);
            }
        });

        buttonSearch.setText("Search");

        jLabel6.setText("Keyword");

        jLabel7.setText("Postcode");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "5 Miles", "10 Miles", "20 Miles", "50Miles" }));

        jLabel8.setText("Distance");

        frameAppointment.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        frameAppointment.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frameAppointment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        frameAppointment.setEnabled(false);
        frameAppointment.setVisible(true);

        buttonConfirmAppointment.setText("Confirm");
        buttonConfirmAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmAppointmentActionPerformed(evt);
            }
        });

        buttonCancelAppointment.setText("Cancel");
        buttonCancelAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelAppointmentActionPerformed(evt);
            }
        });

        jLabel9.setText("Enterprise Name");

        jLabel2.setText("Network");

        jLabel10.setText("Enterprise Type");

        javax.swing.GroupLayout frameAppointmentLayout = new javax.swing.GroupLayout(frameAppointment.getContentPane());
        frameAppointment.getContentPane().setLayout(frameAppointmentLayout);
        frameAppointmentLayout.setHorizontalGroup(
            frameAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameAppointmentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frameAppointmentLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName1))
                    .addGroup(frameAppointmentLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboNetwork1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboType1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addComponent(labAvailable1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labUnavailable1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(frameAppointmentLayout.createSequentialGroup()
                .addComponent(buttonConfirmAppointment)
                .addGap(18, 18, 18)
                .addComponent(buttonCancelAppointment)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        frameAppointmentLayout.setVerticalGroup(
            frameAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameAppointmentLayout.createSequentialGroup()
                .addGroup(frameAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labAvailable1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labUnavailable1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frameAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboNetwork1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(comboType1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(frameAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConfirmAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancelAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frameInquiry, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonInquiry)
                                .addGap(18, 18, 18)
                                .addComponent(buttonAppointment)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(frameAppointment))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(frameInquiry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frameAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetFrameInquiry() {
        frameInquiry.setVisible(false);
        tableClinic.setEnabled(true);
        txtInquiry.setText("");
    }

    private void resetFrameAppointment() {
        frameAppointment.setVisible(false);
        tableClinic.setEnabled(true);
        //TODO
    }

    private void setButtonsEnabled(boolean enable) {
        buttonAppointment.setEnabled(enable);
        buttonInquiry.setEnabled(enable);
    }

    private void buttonAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAppointmentActionPerformed
        if (tableClinic.getSelectedRow() >= 0) {
            Enterprise enterprise = (Enterprise) tableClinic.getValueAt(tableClinic.getSelectedRow(), 0);
            frameAppointment.setVisible(true);
            setButtonsEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a record first");
            return;
        }
    }//GEN-LAST:event_buttonAppointmentActionPerformed

    private void buttonConfirmInquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmInquiryActionPerformed
        if (!userinterface.Util.requireNotEmpty(this, txtInquiry)) {
            return;
        }
        String messageText = txtInquiry.getText();
        InquiryWorkRequest request = new InquiryWorkRequest();
        request.setSenderUsername(account.getUsername());
        request.setMessage(messageText);
        request.setRequestTime(LocalDateTime.now());
        Enterprise enterprise = (Enterprise) tableClinic.getValueAt(tableClinic.getSelectedRow(), 0);
        Organization org = data.OrganizationDAO.searchByTypeAndEnterprise(
            Organization.Type.DentalFrontDesk.getValue(), enterprise.getEnterpriseId());
        if (org == null) {
            JOptionPane.showMessageDialog(this, "The clinic is not setting up properly right now, please try later!");
            return;
        }
        
        request.setReceiverOrganizationId(org.getOrganizationID());
        int requestId = data.WorkRequestDAO.create(request);

        Message message;
        message = new Message();
        message.setFrom(account);
        message.setMessage(messageText);
        message.setSentTime(LocalDateTime.now());
        data.InquiryWorkRequestDAO.create(requestId, message);

        JOptionPane.showMessageDialog(this, "Messasge Sent!");

        resetFrameInquiry();
        setButtonsEnabled(true);
    }//GEN-LAST:event_buttonConfirmInquiryActionPerformed

    private void buttonCancelInquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelInquiryActionPerformed
        frameInquiry.setVisible(false);
        resetFrameInquiry();
        setButtonsEnabled(true);
    }//GEN-LAST:event_buttonCancelInquiryActionPerformed

    private void buttonInquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInquiryActionPerformed
        if (tableClinic.getSelectedRow() >= 0) {
            Enterprise enterprise = (Enterprise) tableClinic.getValueAt(tableClinic.getSelectedRow(), 0);
            frameInquiry.setVisible(true);
            setButtonsEnabled(false);
            tableClinic.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a record first");
            return;
        }
    }//GEN-LAST:event_buttonInquiryActionPerformed

    private void buttonConfirmAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmAppointmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonConfirmAppointmentActionPerformed

    private void buttonCancelAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelAppointmentActionPerformed
        frameAppointment.setVisible(false);
        resetFrameAppointment();
        setButtonsEnabled(true);
    }//GEN-LAST:event_buttonCancelAppointmentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAppointment;
    private javax.swing.JButton buttonCancelAppointment;
    private javax.swing.JButton buttonCancelInquiry;
    private javax.swing.JButton buttonConfirmAppointment;
    private javax.swing.JButton buttonConfirmInquiry;
    private javax.swing.JButton buttonInquiry;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JComboBox comboNetwork1;
    private javax.swing.JComboBox comboType1;
    private javax.swing.JInternalFrame frameAppointment;
    private javax.swing.JInternalFrame frameInquiry;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labAvailable;
    private javax.swing.JLabel labAvailable1;
    private javax.swing.JLabel labUnavailable;
    private javax.swing.JLabel labUnavailable1;
    private javax.swing.JTable tableClinic;
    private javax.swing.JTextArea txtInquiry;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    // End of variables declaration//GEN-END:variables
}
