/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.Customer.CustomerMedicalInfo;
import java.awt.Container;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author z9737
 */
public class MedicalInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPersonalInfoJPanel
     */
    private String username;

    public MedicalInfoJPanel(String username) {
        initComponents();
        this.username = username;

        CustomerMedicalInfo info = data.UserDAO.searchMedicalInfo(username);
        if (info.getGender().equals("M")) {
            radioMale.setSelected(true);
        } else {
            radioFemale.setSelected(true);
        }
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM/dd/yyyy");
        String dateString = info.getDob().format(formatter);
        try {
            Date date;
            date = df.parse(dateString);
            dateDOB.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(MedicalInfoJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (info.isSmoking()) {
            checkboxSmoking.setSelected(true);
        } else {
            checkboxSmoking.setSelected(false);
        }

        if (info.isSweet()) {
            checkboxSweet.setSelected(true);
        } else {
            checkboxSweet.setSelected(false);
        }

        if (info.isDiabetes()) {
            checkboxDiabetes.setSelected(true);
        } else {
            checkboxDiabetes.setSelected(false);
        }

        if (info.isCardio()) {
            checkboxCardio.setSelected(true);
        } else {
            checkboxCardio.setSelected(false);
        }

        if (info.isImmune()) {
            checkboxImmune.setSelected(true);
        } else {
            checkboxImmune.setSelected(false);
        }

        BasicInternalFrameUI ui = (BasicInternalFrameUI) jInternalFrame1.getUI();
        Container north = (Container) ui.getNorthPane();
        north.remove(0);
        north.validate();
        north.repaint();
    }

    /**
     * This method is called state within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        labelHead = new javax.swing.JLabel();
        lblRoutingNo = new javax.swing.JLabel();
        lblRoutingNo1 = new javax.swing.JLabel();
        labelFirstName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        labelDriversLiscence = new javax.swing.JLabel();
        radioMale = new javax.swing.JRadioButton();
        radioFemale = new javax.swing.JRadioButton();
        checkboxSmoking = new javax.swing.JCheckBox();
        checkboxSweet = new javax.swing.JCheckBox();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        labAvailable = new javax.swing.JLabel();
        labUnavailable = new javax.swing.JLabel();
        checkboxDiabetes = new javax.swing.JCheckBox();
        checkboxCardio = new javax.swing.JCheckBox();
        checkboxImmune = new javax.swing.JCheckBox();
        dateDOB = new com.toedter.calendar.JDateChooser();

        labelHead.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelHead.setText("Medical Information");

        lblRoutingNo.setText("Like Eating Sweet");

        lblRoutingNo1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblRoutingNo1.setText("Systemic Disease");

        labelFirstName.setText("Gender *");

        labelLastName.setText("Date of Birth *");

        labelDriversLiscence.setText("Smoking");

        buttonGroupGender.add(radioMale);
        radioMale.setText("Male");
        radioMale.setEnabled(false);

        buttonGroupGender.add(radioFemale);
        radioFemale.setText("Female");
        radioFemale.setEnabled(false);

        checkboxSmoking.setEnabled(false);

        checkboxSweet.setEnabled(false);

        jInternalFrame1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jInternalFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jInternalFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame1.setEnabled(false);
        jInternalFrame1.setMinimumSize(new java.awt.Dimension(100, 25));
        jInternalFrame1.setVisible(true);

        checkboxDiabetes.setText("Diabetes");
        checkboxDiabetes.setEnabled(false);

        checkboxCardio.setText("Cardiovascular Disease");
        checkboxCardio.setEnabled(false);

        checkboxImmune.setText("Other Autoimmune Disorders");
        checkboxImmune.setEnabled(false);
        checkboxImmune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxImmuneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxImmune)
                    .addComponent(checkboxCardio)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(checkboxDiabetes)
                        .addGap(70, 70, 70)
                        .addComponent(labAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labUnavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(checkboxDiabetes))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(labUnavailable, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkboxCardio)
                .addGap(18, 18, 18)
                .addComponent(checkboxImmune)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        dateDOB.setDateFormatString("MM/dd/yyyy");
        dateDOB.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(lblRoutingNo)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelFirstName)
                                    .addGap(18, 18, 18)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelDriversLiscence)
                                    .addComponent(labelLastName))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioMale)
                                .addGap(18, 18, 18)
                                .addComponent(radioFemale))
                            .addComponent(checkboxSmoking)
                            .addComponent(checkboxSweet)
                            .addComponent(dateDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRoutingNo1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelHead)
                        .addGap(60, 60, 60))
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelHead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFirstName)
                    .addComponent(radioMale)
                    .addComponent(radioFemale))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelLastName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(dateDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDriversLiscence)
                    .addComponent(checkboxSmoking))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRoutingNo)
                    .addComponent(checkboxSweet))
                .addGap(34, 34, 34)
                .addComponent(lblRoutingNo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxImmuneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxImmuneActionPerformed
    }//GEN-LAST:event_checkboxImmuneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JCheckBox checkboxCardio;
    private javax.swing.JCheckBox checkboxDiabetes;
    private javax.swing.JCheckBox checkboxImmune;
    private javax.swing.JCheckBox checkboxSmoking;
    private javax.swing.JCheckBox checkboxSweet;
    private com.toedter.calendar.JDateChooser dateDOB;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel labAvailable;
    private javax.swing.JLabel labUnavailable;
    private javax.swing.JLabel labelDriversLiscence;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelHead;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel lblRoutingNo;
    private javax.swing.JLabel lblRoutingNo1;
    private javax.swing.JRadioButton radioFemale;
    private javax.swing.JRadioButton radioMale;
    // End of variables declaration//GEN-END:variables
}
