/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DentalManagerRole;

import Business.Customer.CustomerPersonalInfo;
import Business.Enterprise.Enterprise;
import Business.Organization.DentalCliniclInfo;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Container;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;

/**
 *
 * @author z9737
 */
public class DentalManagerCliniclInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPersonalInfoJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;
    
    private final String ACTION_Add = "ADD";
    private final String ACTION_UPDATE = "UPDATE";
    private String action;
    private DentalCliniclInfo clinicInfo;
    

    public DentalManagerCliniclInfoJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;

        comboState.removeAllItems();
        ArrayList<String> states = data.Data.getAllStates();
        for (String state : states) {
            comboState.addItem(state);
        }

        clinicInfo = data.EnterpriseDAO.searchClinicInfo(enterprise.getEnterpriseId());
        if (clinicInfo == null) {
            action = ACTION_Add;
        } else {
            action = ACTION_UPDATE;
            txtStreet.setText(clinicInfo.getStreet());
            txtCity.setText(clinicInfo.getCity());
            comboState.setSelectedItem(clinicInfo.getState());
            txtPostcode.setText(clinicInfo.getPostcode());
        }
    }

    /**
     * This method is called state within the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHead = new javax.swing.JLabel();
        lblRoutingNo = new javax.swing.JLabel();
        lblAccNo = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        txtPostcode = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lblRoutingNo1 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblRoutingNo2 = new javax.swing.JLabel();
        comboState = new javax.swing.JComboBox<>();

        labelHead.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelHead.setText("Clinic Information");

        lblRoutingNo.setText("Street *");

        lblAccNo.setText("Post Code *");

        txtStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblRoutingNo1.setText("City *");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        lblRoutingNo2.setText("State *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAccNo)
                    .addComponent(lblRoutingNo)
                    .addComponent(lblRoutingNo1)
                    .addComponent(lblRoutingNo2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtStreet)
                    .addComponent(txtCity)
                    .addComponent(txtPostcode)
                    .addComponent(labelHead)
                    .addComponent(comboState, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelHead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreet, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lblRoutingNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lblRoutingNo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboState, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lblRoutingNo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPostcode, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lblAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void txtStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetActionPerformed
    }//GEN-LAST:event_txtStreetActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        txtStreet.setBorder(new LineBorder(new Color(128, 128, 128)));
        txtCity.setBorder(new LineBorder(new Color(128, 128, 128)));
        comboState.setBorder(new LineBorder(new Color(128, 128, 128)));
        txtPostcode.setBorder(new LineBorder(new Color(128, 128, 128)));
     
        if (action.equals(ACTION_Add)) {
            if (!userinterface.Util.requireSeletedItemNotNull(this, comboState)) {
                return;
            }

            if (!userinterface.Util.requireNotEmpty(this, txtStreet, txtCity, txtPostcode)) {
                return;
            }



            if (!userinterface.Util.requirePostcode(this, txtPostcode)) {
                return;
            }

            DentalCliniclInfo clinicInfo = new DentalCliniclInfo();
            clinicInfo.setStreet(txtStreet.getText());
            clinicInfo.setCity(txtCity.getText());
            clinicInfo.setState((String) comboState.getSelectedItem());
            clinicInfo.setPostcode(txtPostcode.getText());
            data.EnterpriseDAO.createClinicInfo(enterprise.getEnterpriseId(), clinicInfo);

            JOptionPane.showMessageDialog(this, "Clinic infomation updated successfully.");
            Container container = this.getParent();
            container.removeAll();
            container.add(new JPanel());
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        } else if (action.equals(ACTION_UPDATE)) {
            if (!userinterface.Util.requireSeletedItemNotNull(this, comboState)) {
                return;
            }

            if (!userinterface.Util.requireNotEmpty(this, txtStreet, txtCity, txtPostcode)) {
                return;
            }
            clinicInfo.setStreet(txtStreet.getText());
            clinicInfo.setCity(txtCity.getText());
            clinicInfo.setState((String) comboState.getSelectedItem());
            clinicInfo.setPostcode(txtPostcode.getText());
            data.EnterpriseDAO.updateClinicInfo(enterprise.getEnterpriseId(), clinicInfo);
            JOptionPane.showMessageDialog(this, "Personal infomation updated successfully.");
            Container container = this.getParent();
            container.removeAll();
            container.add(new JPanel());
            CardLayout layout = (CardLayout) container.getLayout();
            layout.next(container);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
    }//GEN-LAST:event_txtCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboState;
    private javax.swing.JLabel labelHead;
    private javax.swing.JLabel lblAccNo;
    private javax.swing.JLabel lblRoutingNo;
    private javax.swing.JLabel lblRoutingNo1;
    private javax.swing.JLabel lblRoutingNo2;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtPostcode;
    private javax.swing.JTextField txtStreet;
    // End of variables declaration//GEN-END:variables
}
